### ISSUE TITLE
Uninitialized constant Puzzle::Configuration::OpenSSL

### ISSUE THREAD

**Issue by sdball** [gingman/puzzle#1]
I'm running into this while trying out the gem in irb. After the configuration block:

```
NameError: uninitialized constant Puzzle::Configuration::OpenSSL
  from puzzle-0.3.0/lib/puzzle/configuration.rb:30
```

**Comment by gingman** [comment]
Do you have ruby compiled with ssl enabled? If you are using RVM, you can try the informationa vailable here: https://rvm.io/packages/openssl/

If this doesn't work, you might need to point to a correct certificate file. In the configuration block, you have access to ca_file and ca_path. You can see the default values in lib/puzzle/configuration.rb. You can check to see if they match with your current OS.
